apiVersion: v1
kind: ConfigMap
metadata:
  name: config-features
  namespace: knative-serving
data:
  kubernetes.podspec-fieldref: "enabled"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-autoscaler
  namespace: knative-serving
data:
  allow-zero-initial-scale: "true"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-praas
  namespace: knative-serving
data:
  container-image: "public.ecr.aws/s4f6z1l2/praas/container:latest"
  redis-address: "redis-cluster.praas:6379"

---