apiVersion: v1
kind: ConfigMap
metadata:
  name: config-praas
  namespace: praas
data:
  container-image: "kind.local/container-test:latest"
  container-namespace: "default"
  container-coord-endpoint: "/coordinate/peers"
  container-metrics-endpoint: "/custom-metrics"
  container-restart-endpoint: "/restart"
  container-swap-endpoint: "/swap"
  container-port: "8080"
  redis-address: "redis-cluster.praas:6379"
  metric-time: "30"
  max-funcs-per-process: "2"
  # cpu-limit: "4"
  # mem-limit: "4Gi"
---