apiVersion: apps/v1
kind: Deployment
metadata:
  name: praas-workflow
  namespace: praas
spec:
  selector:
    matchLabels:
      app: praas-workflow
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: praas-workflow
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: praas-workflow
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: executor
          image: public.ecr.aws/s4f6z1l2/praas/workflow-executor:latest
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: praas-workflow
  name: praas-workflow
  namespace: praas
spec:
  type: LoadBalancer
  ports:
    - name: http-requests
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: praas-workflow