kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: praas-process-admin
  labels:
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: praas
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "configmaps"]
    verbs: ["get", "list", "create", "update", "delete", "deletecollection", "patch", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: praas
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: praas
    app.kubernetes.io/version: devel
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: praas-controller-admin
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: praas
    app.kubernetes.io/version: devel
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: praas
roleRef:
  kind: ClusterRole
  name: praas-process-admin
  apiGroup: rbac.authorization.k8s.io